import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { Input } from '@chakra-ui/react';
import { Button, ButtonGroup } from '@chakra-ui/react';
import { useState } from 'react';
import {
  List,
  ListItem,
  ListIcon,
  OrderedList,
  UnorderedList,
} from '@chakra-ui/react'

export default function Home({data}) {
  const[value, setValue] = useState(""); 
  const [myList, setMyList ] = useState(["AB", "AC"]);

  async function addToMyList(){
    const response = await fetch(
      `https://api.edamam.com/api/recipes/v2?type=public&q=${value}&app_id=14f8dadb&app_key=69a812c28b3179d4353e2b5292b16487`
    );
    const data = await response.json();
    // myList.push(value);
    // console.log(myList);
    console.log(data);
    let info = data.hits.map((item)=>{ return item.recipe});
    info.map((item)=>{ console.log(item.label, item.url, item.image)})
    // console.log(data._links.next.href);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div>
          <Input placeholder='Your Recipe' value={value}  onChange={(e) => {setValue(e.target.value)}}/>
          <Button colorScheme='blue' onClick={addToMyList}>Add</Button>
        </div>

        <div>
              <List spacing={3}>
                  {myList.map((item, index)=> { return(<ListItem key={index}>
                    <ListIcon color='green.500' />
                    {item};
                  </ListItem>)})}
              </List>
        </div>
      </main>
    </div>
  )
}


export async function getServerSideProps() {
  const response = await fetch(
    "https://api.edamam.com/api/recipes/v2?type=public&q=mashroom&app_id=14f8dadb&app_key=69a812c28b3179d4353e2b5292b16487"
  );

  const data = await response.json();
  console.log(data);
  return {
    props: { data: data },
  };
}